# Generated by Django 3.2.9 on 2021-12-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='model',
            new_name='done',
        ),
    ]
